### ISSUE TITLE
Extracted proposal ID and motion ID should be different (motion extraction reworking)

### ISSUE THREAD

**Issue by sandervh14** [transparentdemocracy/voting-data#22]
They have been assigned one and the same ID in the past week or so, but both proposal and motion have a separate ID in the plenary reports.

Due to the implementation currently, we save proposal and motion as a 1-1 relationship. This means that if a proposal got several motions (for amendments), we will create duplicate proposals in our JSON output data to the website team.

Related to this, and would be nice to cover this as well in the meantime: several motions can be done on one proposal. If we would capture this, we will store amendment votes as well.

Would also be nice and may even follow logically from the above work: pulling apart the creation of motions and proposals. They are now heavily intertwinedly created in the same method in extraction.py.

**Comment by karel1980** [comment]
Before continuing and changing the model I'd like to make sure I understand things better.

[lexicon](https://www.dekamer.be/toegankelijk/laChambre_lexique.htm) explains some terms like motion and proposal, but finding out which is which in the plenary reports is still unclear to me.

The numbers with solid black border indicate different sections, but they're not the key to understanding the document structure... E.g. The section "Naamstemmingen" in plenary 298 starts between 09.01 and 09.02.
They usually indicate a change of speaker, but sometimes the speaker is announced beforehand (particularly the chairman)

I'm going to sleep on it, but perhaps a short sparring session would also be productive

**Comment by karel1980** [comment]
More observations: Plenary 298, item 10 mentions 3 motions, but only 1 is voted on because it has legal priority (sorry if this is a naive translation). The other 2 motions are 'vervallen / caduques'

Item 14 has many amendments, many have votes, but other simply reuse the result of a previous vote (e.g. stemming/vote 6). The text makes this clear. For parsing, the actual vote is in a table with a border around it - the 'reused' vote just contain a reference to the earlier vote.

**Comment by sandervh14** [comment]
Interesting, I had not taken the time to read that lexicon yet, but it's worth it. We can inspire our next work with a better understaning based on that.

Thanks for your pointers. I used to think that the numbers "in borders" in the vote section agreed with the numbers in the section with the propositions. I see now that this does not always agree.

On the other hand, when looking at the text better now too, I think finding referenced documents will be "easier" than I thought. :-)

Yes, let's do the sparring session. I even ideally would like to do it in a Sherlock-style with print and a red marker indicating stuff and making links etc, but it's a lot of pages. Let's just discuss tomorrow and put our understanding together.

**Comment by sandervh14** [comment]
We're currently working on this. The implementation of motion extraction is being re-worked, see main branch.

**Comment by sandervh14** [comment]
This is implemented now. See https://github.com/transparentdemocracy/voting-data/blob/main/data/output/plenary/json/plenaries.json.
