### ISSUE TITLE
Make markdown serializer append votes again to each plenary xxx.md file

### ISSUE THREAD

**Issue by sandervh14** [transparentdemocracy/voting-data#23]
This broke after the update of model.py.

The markdown at the moment is the only "proof" to the outside world of which voting info we are capable of extracting, for as long the website prototype is not up and running.
It's therefore important we keep the markdown dumps contain the actual yes, no and abstention votes.
I've now commented that in my changes of this evening, as after the refactoring, it requires finding the right "proposal xxx.md" file and appending the votes there.

**Comment by karel1980** [comment]
Added back voters to markdown

**Comment by sandervh14** [comment]
Great!
