### ISSUE TITLE
Add party information in JSON

### ISSUE THREAD

**Issue by sandervh14** [transparentdemocracy/voting-data#26]
This is important info, used in the mockups.

Karel wrote enrichment to download politicians ("actors") and their party affiliations.
Add this party information in the votes.json.
Or: would be better to reduce the votes.json size: adding a politicians.json and linking in every vote from votes.json to politicians.json with a politician_id.

**Comment by karel1980** [comment]
I've changed votes.json so it only contains the politician ids.
This brings the file size down by about 50%.

I've also changed vote extraction so we don't discard all votes when we can't parse the vote results exactly. Doing this gives us results that are closer to reality.

**Comment by karel1980** [comment]
@sandervh14 please review and close if you're okay with this.

**Comment by karel1980** [comment]
Also committed the politicians json which contains id, full name and party (generated using td-politicians-json)

**Comment by sandervh14** [comment]
Great work! You were on a roll!! 😄 

There were only 2 minor things I noticed for improvement, and they are only improvements for the longer term: #30 and #31.
