### ISSUE TITLE
Plenary date field needed in plenaries.json

### ISSUE THREAD

**Issue by MrFranksJr** [transparentdemocracy/voting-data#32]
In order to properly display the date of certain motions, plenaries, etc... in the front-end, we would need this data to be available in the source json. Currently this is not the case.

**Comment by karel1980** [comment]
I've added the plenary date field. The json wasn't updated in the repository. Follow the readme and run td-plenaries-json if you want updated shizzle

**Comment by sandervh14** [comment]
Karel fixed this, and the new json resulting from that and other changes is generated now. We can close this issue.
