### ISSUE TITLE
Not all input reports & motions (votings) are fetched currently

### ISSUE THREAD

**Issue by sandervh14** [transparentdemocracy/voting-data#4]
Find out why some are skipped / not properly processed.

**Comment by karel1980** [comment]
It's not perfect, but none of the files are currently failing. Are there any specific problems that we should address in scope of this issue?

**Comment by sandervh14** [comment]
I created this issue when the HTML extractor didn't exist yet.
As we both know, that one works better, due to less PDF processing artefacts.
I'll have a look in the coming days if there are still unexpected results.
Note to self: start with checking what is still logged with "failed to process %s".

**Comment by sandervh14** [comment]
I'll close this issue. We're have identified and will still identify reports that haven't been processed the way we expected them to be, and turned that (or will turn them) into additional unit tests.
So, ongoing, but we don't need a separate issue for this anymore. We're on it as part of our other work.
