### ISSUE TITLE
Motion title NF and FR are swapped

### ISSUE THREAD

**Issue by GuidoDechamps** [transparentdemocracy/voting-data#41]
In motiongroup, the motions sometimes have their titles swapped. NF is in French and vice versa. But not always the case

```
{
"id": "55_160_mg_20_m0",
            "sequence_number": "0",
            "title_nl": "Cette interpellation a été développée en réunion publique de la commission des Relations extérieures du 26 janvier 2022.",
            "title_fr": "Deze interpellatie werd gehouden in de openbare vergadering van de commissie voor Buitenlandse Betrekkingen van 26 januari 2022.",
}
```

**Comment by karel1980** [comment]
Should be fixed, but it's using a simple heuristic based on information in the html tags. It's gonna be GIGO compliant.
If you spot more violations, please keep reporting them, so we can add test cases to finetune (and eventually we'll do language detection based on content to overcome data quality problems)
